export function HelpPage() {
  return (
    <div className="v-page v-help-page">
      <div className="v-section-header">
        <h2>Help, AI Safety & Disclaimers</h2>
        <p>Learn about Vericla's safety architecture, evidence verification, and privacy model.</p>
      </div>

      <div className="v-help-grid">
        <div className="v-card">
          <div className="v-card-header">
            <span className="v-card-icon">⚖️</span>
            <h3>Legal Information Assistant Disclaimer</h3>
          </div>
          <p className="v-card-desc">
            Vericla is an AI-powered legal document intelligence assistant designed to help users understand
            document structure, extract clauses, and review party obligations.
          </p>
          <div className="v-disclaimer-box">
            <strong>Important Notice:</strong> Vericla is NOT a lawyer and does NOT provide definitive legal advice.
            Analysis summaries and review signals are generated for information purposes only and should be reviewed
            by qualified legal counsel before taking legal action.
          </div>
        </div>

        <div className="v-card">
          <div className="v-card-header">
            <span className="v-card-icon">📍</span>
            <h3>Evidence-First Traceability</h3>
          </div>
          <p className="v-card-desc">
            Every clause, obligation, and review signal generated by Vericla is linked to exact source evidence.
          </p>
          <ul className="v-help-list">
            <li>
              <strong>Deterministic Offsets:</strong> Text chunks preserve exact character offsets matching original documents.
            </li>
            <li>
              <strong>Anti-Hallucination Boundary:</strong> AI citations are verified against source text before display.
            </li>
            <li>
              <strong>Page Metadata:</strong> Page numbers are tracked for PDF files.
            </li>
          </ul>
        </div>

        <div className="v-card">
          <div className="v-card-header">
            <span className="v-card-icon">🛡️</span>
            <h3>Prompt Injection Protection</h3>
          </div>
          <p className="v-card-desc">
            Uploaded documents are treated as untrusted data.
          </p>
          <p className="v-card-desc">
            Vericla employs 4-layer structural prompt boundaries that instruct the AI to ignore any embedded commands
            or instructions (e.g., "Ignore previous instructions") inside uploaded document text.
          </p>
        </div>

        <div className="v-card">
          <div className="v-card-header">
            <span className="v-card-icon">⚡</span>
            <h3>Ephemeral Data Privacy</h3>
          </div>
          <p className="v-card-desc">
            Your uploaded documents are processed in-memory only. Vericla does not store documents in permanent databases
            or use your confidential legal text for public AI model training.
          </p>
        </div>
      </div>
    </div>
  )
}
